### ISSUE TITLE
Error al comenzar pug

### ISSUE THREAD

**Issue by Hakkehify** [leobrines/pug_for_cs#1]
Por alguna razon cuando intento forzar a que inicie el pug o cuando estamos los 10 jugadores el plugin se bugea y no comienza. Probe tanto con la release como con la ultima version posteada y todas dan el mismo error, Aqui el log de la consola

L 08/02/2019 - 05:00:59: [AMXX] Displaying debug trace (plugin "competitive.amxx")

L 08/02/2019 - 05:00:59: [AMXX] Run time error 4: index out of bounds 

L 08/02/2019 - 05:00:59: [AMXX]    [0] competitive.sma::maps_create_menu (line 624)

L 08/02/2019 - 05:00:59: [AMXX]    [1] competitive.sma::fnStartVoteMap (line 321)

L 08/02/2019 - 05:00:59: [AMXX]    [2] competitive.sma::fnNextVote (line 299)

L 08/02/2019 - 05:00:59: [AMXX]    [3] competitive.sma::PugStart (line 286)

L 08/02/2019 - 05:00:59: [AMXX]    [4] competitive.sma::PugStart (line 281)

**Comment by leobrines** [comment]
Hakkehify, te agredezco mucho por reportar el issue!

Parece ser un error al crear el menu de mapas para escogerlo. Me puedes responder cuantos mapas estas usando en mapcycle.txt o maps.ini?

**Comment by Hakkehify** [comment]
Tengo estos, Quise probar el mod antes de comenzar a editar todo por eso no cambie mapas
de_airstrip
cs_havana
de_chateau
de_aztec
as_oilrig
cs_siege
de_cbble
de_dust
cs_747
de_prodigy
cs_assault
cs_office
cs_italy
cs_backalley
cs_militia
de_train

**Comment by leobrines** [comment]
Claro, entiendo.

El problema es que el plugin soporta como máximo 15 mapas (nada especial). Se puede editar en el archivo scripting/competitive.sma linea 21 y 22.

Actualmente son 15
```
new g_sMapNames[15][32]
new g_iMapVotes[15]
```

Lo subire a 25, asi los proximos testers pueden usar el plugin con el servidor default .

Gracias!

**Comment by Hakkehify** [comment]
Ah, vale muchas gracias. por cierto aprovecho y aviso que en el txt de lenguajes en el apartado de ingles faltan definir unos mensajes

**Comment by leobrines** [comment]
**Ya actualicé el competitive.sma**

Gracias por el reporte
Cierro issue
