### ISSUE TITLE
 how to activate captain mod?

### ISSUE THREAD

**Issue by WessTorn** [leobrines/pug_for_cs#5]
Hi leobrines, how to activate captain mod?

**Comment by leobrines** [comment]
Hi Wess, for now there is no captain mod. It is a feature to implement

Thanks for watching pugmod

**Comment by WessTorn** [comment]
Very cool pug mod when you think to make a captain?

Sorry for the English (Google Translate)

**Comment by leobrines** [comment]
Thansk bro! I also use google translate so don't worry haha.

Well I don't have a certain time to do it haha. But if you need it so much I add it :p

**Comment by WessTorn** [comment]
I do not want to prove myself bad and make you do it now :(
When you have some free time, make a captain mod please.
Good luck in future developments :)
