### ISSUE TITLE
los nosteam no pueden entrar

### ISSUE THREAD

**Issue by darth19** [leobrines/pug_for_cs#6]
hola los nosteam no pueden entrar al server con la ultima version :(

error : Host_Error: UserMsg: Not Present on Client 58

**Comment by hellnano** [comment]
> hola los nosteam no pueden entrar al server con la ultima version :(
> 
> error : Host_Error: UserMsg: Not Present on Client 58

Eso se debe a que en esta ultima version hay presencia del "query_client_cvar", que regula los cl_rate (los rates de los jugadores) y eso solo se puede hacer en las últimas versiones del CS1.6 (Steam).

tienes 2 caminos.
1.- Forzar a la gente a comprarse el CS1.6 Orginal en la campaña de navidad (estará a 1 dolar)
2.- Limpiar el código tu mismo y borrar toda llamada a los "query_client_cvar" y volverlo a compilar. (Si no sabes o no puedes, te toca hacer el paso 1).

**Comment by leobrines** [comment]
Agregue una cvar pug_allow_nonsteam se puede configurar en 0 o en 1. Esto fixea el error con las cuentas non steam
